In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
app_new = application_df.drop(columns=['EIN', 'NAME'])
app_new.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
u_counts = app_new.nunique()
u_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
app_new['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
cutoff_value = 200
application_type_counts = app_new['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()
# Replace in dataframe
for app in application_types_to_replace:
    app_new['APPLICATION_TYPE'] = app_new['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_new['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
app_new['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
cutoff_value = 200
classifications_type_counts = app_new['CLASSIFICATION'].value_counts()
classifications_to_replace = classifications_type_counts[classifications_type_counts < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    app_new['CLASSIFICATION'] = app_new['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
app_new['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1197
C7000      777
C1700      287
Name: CLASSIFICATION, dtype: int64

In [12]:
df_encoded = pd.get_dummies(app_new)
df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [37]:
X = df_encoded.drop(columns=['IS_SUCCESSFUL', 'INCOME_AMT_50M+','INCOME_AMT_5M-10M', 'SPECIAL_CONSIDERATIONS_Y', 'SPECIAL_CONSIDERATIONS_N'], axis=1)
y = df_encoded['IS_SUCCESSFUL']

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [39]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [51]:
nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units=100, input_dim=41, activation='relu'))
nn.add(tf.keras.layers.Dense(units=30, activation='sigmoid'))
nn.add(tf.keras.layers.Dense(units=30, activation='linear'))
nn.add(tf.keras.layers.Dense(units=30, activation='tanh'))

nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_57 (Dense)            (None, 100)               4200

 dense_58 (Dense)            (None, 30)                3030

 dense_59 (Dense)            (None, 30)                930

 dense_60 (Dense)            (None, 30)                930

 dense_61 (Dense)            (None, 1)                 31

=================================================================
Total params: 9,121
Trainable params: 9,121
Non-trainable params: 0
_________________________________________________________________

In [52]:
nn.compile(
    loss = 'binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [53]:
nn.fit(X_train_scaled, y_train, epochs=20)
#nn.fit(X_train_scaled, y_train, epochs=80)
#nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/20
858/858 [==============================] - 4s 3ms/step - loss: 0.5700 - accuracy: 0.7210
Epoch 2/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5554 - accuracy: 0.7287
Epoch 3/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7295
Epoch 4/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7309
Epoch 5/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7318
Epoch 6/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7328
Epoch 7/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7300
Epoch 8/20
858/858 [==============================] - 3s 3ms/step - loss: 0.5474 - accuracy: 0.7319
Epoch 9/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7307
Epoch 10/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7326
Epoch 11/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7331
Epoch 12/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7330
Epoch 13/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7330
Epoch 14/20
858/858 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7339
Epoch 15/20
858/858 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7348
Epoch 16/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7340
Epoch 17/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7350
Epoch 18/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7353
Epoch 19/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7345
Epoch 20/20
858/858 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7342

In [54]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5553 - accuracy: 0.7257 - 423ms/epoch - 2ms/step
Loss: 0.555263340473175, Accuracy: 0.7256559729576111

In [55]:
nn.save('AlphabetSoupCharity_Optimization.h5')